# Generated by Django 5.1 on 2024-09-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink1', models.IntegerField(default=0)),
                ('drink2', models.IntegerField(default=0)),
                ('todo1', models.BooleanField(default=False)),
                ('todo2', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
